export const doctors = [
  {
    id: 1,
    name: 'Dr. Sarah Johnson',
    specialty: 'Orthodontist',
    experience: '10 years',
    education: 'Harvard Dental School',
    image: '/images/doctors/sarah-johnson.jpg',
    bio: 'Dr. Sarah specializes in braces and aligners, creating beautiful smiles for patients of all ages.',
    rating: 4.9,
    reviews: 45,
    availability: ['Mon', 'Wed', 'Fri'],
  },
  {
    id: 2,
    name: 'Dr. Michael Chen',
    specialty: 'Oral Surgeon',
    experience: '15 years',
    education: 'UCLA Dental School',
    image: '/images/doctors/michael-chen.jpg',
    bio: 'Dr. Michael is an expert in dental implants and complex surgical procedures.',
    rating: 4.8,
    reviews: 38,
    availability: ['Tue', 'Thu', 'Sat'],
  },
  {
    id: 3,
    name: 'Dr. Emily Rodriguez',
    specialty: 'Pediatric Dentist',
    experience: '8 years',
    education: 'Columbia Dental School',
    image: '/images/doctors/emily-rodriguez.jpg',
    bio: 'Dr. Emily loves working with children, making dental visits fun and stress-free.',
    rating: 4.9,
    reviews: 52,
    availability: ['Mon', 'Tue', 'Wed', 'Thu'],
  },
  {
    id: 4,
    name: 'Dr. David Kim',
    specialty: 'Cosmetic Dentist',
    experience: '12 years',
    education: 'NYU Dental School',
    image: '/images/doctors/david-kim.jpg',
    bio: 'Dr. David transforms smiles with advanced cosmetic dentistry techniques.',
    rating: 4.7,
    reviews: 29,
    availability: ['Mon', 'Fri', 'Sat'],
  },
];