export const services = [
  {
    id: 1,
    title: 'Teeth Cleaning',
    description: 'Professional cleaning to remove plaque and tartar for a brighter smile.',
    icon: '🦷',
    price: '$100',
    duration: '30 mins',
    category: 'Preventive',
  },
  {
    id: 2,
    title: 'Root Canal',
    description: 'Advanced treatment for infected tooth pulp to save your natural tooth.',
    icon: '🦷',
    price: '$500',
    duration: '60 mins',
    category: 'Restorative',
  },
  {
    id: 3,
    title: 'Dental Implants',
    description: 'Permanent solution for missing teeth with natural-looking results.',
    icon: '🦷',
    price: '$2,000',
    duration: '90 mins',
    category: 'Surgical',
  },
  {
    id: 4,
    title: 'Braces',
    description: 'Straighten teeth and perfect your smile with modern orthodontic solutions.',
    icon: '🦷',
    price: '$3,000',
    duration: '90 mins',
    category: 'Orthodontic',
  },
  {
    id: 5,
    title: 'Teeth Whitening',
    description: 'Professional whitening treatment for a brighter, more confident smile.',
    icon: '🦷',
    price: '$300',
    duration: '45 mins',
    category: 'Cosmetic',
  },
  {
    id: 6,
    title: 'Dental Crowns',
    description: 'Restore damaged or decayed teeth with durable, natural-looking crowns.',
    icon: '🦷',
    price: '$800',
    duration: '60 mins',
    category: 'Restorative',
  },
];